### ISSUE TITLE
Please fix these issues in code / readme

### ISSUE THREAD

**Issue by nitinmukesh** [rlgnswk/NeRFFaceSpeech_Code#4]
Some errors can be fixed, without that it will not work for Linux or Windows users

1.
Fix path in code (it is currently hardcoded) [model_path = '/home/gihoon/NeRFFaceSpeech_CVPR/pretrained_networks/BFM_for_3DMM-Fitting-Pytorch/BFM/BFM09_model_info.mat']

NeRFFaceSpeech_Code\3DMM-Fitting-Pytorch\core\__init__.py
model_path = './pretrained_networks/BFM_for_3DMM-Fitting-Pytorch/BFM/BFM09_model_info.mat' 

2. Missing checkpoint (plz include in Readme)
Download SadTalker_V0.0.2_256.safetensors
https://github.com/OpenTalker/SadTalker/releases
to
NeRFFaceSpeech_Code\pretrained_networks\sad_talker_pretrained

3. Missing file (plz include in Readme)
Download
https://huggingface.co/wsj1995/sadTalker/blob/af80749f8c9af3702fbd0272df14ff086986a1de/BFM09_model_info.mat
to
NeRFFaceSpeech_Code\pretrained_networks\BFM_for_3DMM-Fitting-Pytorch\BFM

4.
Please fix the inference command, incorrect path of audio file

python StyleNeRF/main_NeRFFaceSpeech_audio_driven_from_image.py   \
    --outdir=out_test --trunc=0.7 \
        --network=pretrained_networks/ffhq_1024.pkl \
            --test_data="test_data/test_audio/AdamSchiff_0.wav" \
                --test_img="test_data/test_img/32.png"

**Comment by rlgnswk** [comment]
We've done. Thank you for sharing your experiences!

**Comment by nitinmukesh** [comment]
Thank you. I was about to raise PR but you are very fast.
