### ISSUE TITLE
Training Code/Instructions?

### ISSUE THREAD

**Issue by starc52** [rlgnswk/NeRFFaceSpeech_Code#6]
Hi!
Kudos to you for the awesome project! I was looking to test the model out on a custom dataset and watned to train from scratch. However, there is no code or instructions available for that. Are you guys going to release the training code for this?

**Comment by rlgnswk** [comment]
Hello!

There's no need to train on the custom dataset as we proposed a one-shot method. However, you need to match the data format. Just follow the format described in the "Custom Data for Use" section of the readme.

If it's about LipaintNet, no new data is required, but I recommend trying to implement the training code as outlined in the paper.

**Comment by starc52** [comment]
Thanks!
